disabled_rules:
- trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

line_length:
- 200

function_parameter_count:
- 10
- 15

file_length:
- 500

type_body_length:
- 400
- 450

